
include: package:flutter_lints/flutter.yaml

linter:  
  rules:
      prefer_const_constructors: true
      prefer_const_declarations: true
      prefer_const_literals_to_create_immutables: true
      use_null_aware_elements: true
    

formatter:
  trailing_commas: preserve
  page_width: 120
